//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Задача по гражданину.
    /// </summary>
    //  *** Start programmer edit section *** (ЗадачаПоГражданину CustomAttributes)

    //  *** End programmer edit section *** (ЗадачаПоГражданину CustomAttributes)
    [AutoAltered()]
    [Caption("Задача по гражданину")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗадачаПоГражданинуE", new string[0])]
    public class ЗадачаПоГражданину : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CZN.КарточкаГражданина fКарточкаГКарточкаГражданинаражданина;
        
        //  *** Start programmer edit section *** (ЗадачаПоГражданину CustomMembers)

        //  *** End programmer edit section *** (ЗадачаПоГражданину CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CZN.КарточкаГражданина.
        /// </summary>
        //  *** Start programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина CustomAttributes)

        //  *** End programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CZN.КарточкаГражданина КарточкаГКарточкаГражданинаражданина
        {
            get
            {
                //  *** Start programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Get start)

                //  *** End programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Get start)
                IIS.CZN.КарточкаГражданина result = this.fКарточкаГКарточкаГражданинаражданина;
                //  *** Start programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Get end)

                //  *** End programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Set start)

                //  *** End programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Set start)
                this.fКарточкаГКарточкаГражданинаражданина = value;
                //  *** Start programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Set end)

                //  *** End programmer edit section *** (ЗадачаПоГражданину.КарточкаГКарточкаГражданинаражданина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗадачаПоГражданинуE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗадачаПоГражданинуE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗадачаПоГражданинуE", typeof(IIS.CZN.ЗадачаПоГражданину));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗадачаПоГражданину.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfЗадачаПоГражданину CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfЗадачаПоГражданину CustomAttributes)
    public class DetailArrayOfЗадачаПоГражданину : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CZN.DetailArrayOfЗадачаПоГражданину members)

        //  *** End programmer edit section *** (IIS.CZN.DetailArrayOfЗадачаПоГражданину members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗадачаПоГражданину by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗадачаПоГражданину.
        /// </summary>
        public DetailArrayOfЗадачаПоГражданину(IIS.CZN.КарточкаГражданина fКарточкаГражданина) : 
                base(typeof(ЗадачаПоГражданину), ((ICSSoft.STORMNET.DataObject)(fКарточкаГражданина)))
        {
        }
        
        public IIS.CZN.ЗадачаПоГражданину this[int index]
        {
            get
            {
                return ((IIS.CZN.ЗадачаПоГражданину)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CZN.ЗадачаПоГражданину dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
