//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Карточка гражданина.
    /// </summary>
    //  *** Start programmer edit section *** (Карточка гражданина CustomAttributes)

    //  *** End programmer edit section *** (Карточка гражданина CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Карточка гражданинаE", new string[] {
            "ДатаПриема as \'Дата приема\'",
            "Личность as \'Личность\'",
            "Личность.ФИО as \'ФИО\'"})]
    [AssociatedDetailViewAttribute("Карточка гражданинаE", "НаправлениеГражданина", "НаправлениеГражданинаE", true, "", "Направление гражданина", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("Карточка гражданинаE", "ЗадачаПоГражданину", "ЗадачаПоГражданинуE", true, "", "Задача по гражданину", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("Карточка гражданинаE", "ПередачаКарточки", "ПередачаКарточкиE", true, "", "Передача карточки", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("Карточка гражданинаE", "ЯвкаГражданина", "ЯвкаГражданинаE", true, "", "Явка гражданина", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("Карточка гражданинаE", "ОтметкаГражданина", "ОтметкаГражданинаE", true, "", "Отметка гражданина", true, new string[] {
            ""})]
    [View("Карточка гражданинаL", new string[] {
            "ДатаПриема as \'Дата приема\'",
            "Личность.ФИО as \'ФИО\'"})]
    public class Карточка гражданина : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПриема;
        
        private IIS.CZN.Личность fЛичность;
        
        private IIS.CZN.DetailArrayOfНаправлениеГражданина fНаправлениеГражданина;
        
        private IIS.CZN.DetailArrayOfЗадачаПоГражданину fЗадачаПоГражданину;
        
        private IIS.CZN.DetailArrayOfПередачаКарточки fПередачаКарточки;
        
        private IIS.CZN.DetailArrayOfЯвкаГражданина fЯвкаГражданина;
        
        private IIS.CZN.DetailArrayOfОтметкаГражданина fОтметкаГражданина;
        
        //  *** Start programmer edit section *** (Карточка гражданина CustomMembers)

        //  *** End programmer edit section *** (Карточка гражданина CustomMembers)

        
        /// <summary>
        /// ДатаПриема.
        /// </summary>
        //  *** Start programmer edit section *** (Карточка гражданина.ДатаПриема CustomAttributes)

        //  *** End programmer edit section *** (Карточка гражданина.ДатаПриема CustomAttributes)
        public virtual System.DateTime ДатаПриема
        {
            get
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ДатаПриема Get start)

                //  *** End programmer edit section *** (Карточка гражданина.ДатаПриема Get start)
                System.DateTime result = this.fДатаПриема;
                //  *** Start programmer edit section *** (Карточка гражданина.ДатаПриема Get end)

                //  *** End programmer edit section *** (Карточка гражданина.ДатаПриема Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ДатаПриема Set start)

                //  *** End programmer edit section *** (Карточка гражданина.ДатаПриема Set start)
                this.fДатаПриема = value;
                //  *** Start programmer edit section *** (Карточка гражданина.ДатаПриема Set end)

                //  *** End programmer edit section *** (Карточка гражданина.ДатаПриема Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (Карточка гражданина.Личность CustomAttributes)

        //  *** End programmer edit section *** (Карточка гражданина.Личность CustomAttributes)
        [NotNull()]
        public virtual IIS.CZN.Личность Личность
        {
            get
            {
                //  *** Start programmer edit section *** (Карточка гражданина.Личность Get start)

                //  *** End programmer edit section *** (Карточка гражданина.Личность Get start)
                IIS.CZN.Личность result = this.fЛичность;
                //  *** Start programmer edit section *** (Карточка гражданина.Личность Get end)

                //  *** End programmer edit section *** (Карточка гражданина.Личность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Карточка гражданина.Личность Set start)

                //  *** End programmer edit section *** (Карточка гражданина.Личность Set start)
                this.fЛичность = value;
                //  *** Start programmer edit section *** (Карточка гражданина.Личность Set end)

                //  *** End programmer edit section *** (Карточка гражданина.Личность Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (Карточка гражданина.НаправлениеГражданина CustomAttributes)

        //  *** End programmer edit section *** (Карточка гражданина.НаправлениеГражданина CustomAttributes)
        public virtual IIS.CZN.DetailArrayOfНаправлениеГражданина НаправлениеГражданина
        {
            get
            {
                //  *** Start programmer edit section *** (Карточка гражданина.НаправлениеГражданина Get start)

                //  *** End programmer edit section *** (Карточка гражданина.НаправлениеГражданина Get start)
                if ((this.fНаправлениеГражданина == null))
                {
                    this.fНаправлениеГражданина = new IIS.CZN.DetailArrayOfНаправлениеГражданина(this);
                }
                IIS.CZN.DetailArrayOfНаправлениеГражданина result = this.fНаправлениеГражданина;
                //  *** Start programmer edit section *** (Карточка гражданина.НаправлениеГражданина Get end)

                //  *** End programmer edit section *** (Карточка гражданина.НаправлениеГражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Карточка гражданина.НаправлениеГражданина Set start)

                //  *** End programmer edit section *** (Карточка гражданина.НаправлениеГражданина Set start)
                this.fНаправлениеГражданина = value;
                //  *** Start programmer edit section *** (Карточка гражданина.НаправлениеГражданина Set end)

                //  *** End programmer edit section *** (Карточка гражданина.НаправлениеГражданина Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину CustomAttributes)

        //  *** End programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину CustomAttributes)
        public virtual IIS.CZN.DetailArrayOfЗадачаПоГражданину ЗадачаПоГражданину
        {
            get
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Get start)

                //  *** End programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Get start)
                if ((this.fЗадачаПоГражданину == null))
                {
                    this.fЗадачаПоГражданину = new IIS.CZN.DetailArrayOfЗадачаПоГражданину(this);
                }
                IIS.CZN.DetailArrayOfЗадачаПоГражданину result = this.fЗадачаПоГражданину;
                //  *** Start programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Get end)

                //  *** End programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Set start)

                //  *** End programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Set start)
                this.fЗадачаПоГражданину = value;
                //  *** Start programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Set end)

                //  *** End programmer edit section *** (Карточка гражданина.ЗадачаПоГражданину Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (Карточка гражданина.ПередачаКарточки CustomAttributes)

        //  *** End programmer edit section *** (Карточка гражданина.ПередачаКарточки CustomAttributes)
        public virtual IIS.CZN.DetailArrayOfПередачаКарточки ПередачаКарточки
        {
            get
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ПередачаКарточки Get start)

                //  *** End programmer edit section *** (Карточка гражданина.ПередачаКарточки Get start)
                if ((this.fПередачаКарточки == null))
                {
                    this.fПередачаКарточки = new IIS.CZN.DetailArrayOfПередачаКарточки(this);
                }
                IIS.CZN.DetailArrayOfПередачаКарточки result = this.fПередачаКарточки;
                //  *** Start programmer edit section *** (Карточка гражданина.ПередачаКарточки Get end)

                //  *** End programmer edit section *** (Карточка гражданина.ПередачаКарточки Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ПередачаКарточки Set start)

                //  *** End programmer edit section *** (Карточка гражданина.ПередачаКарточки Set start)
                this.fПередачаКарточки = value;
                //  *** Start programmer edit section *** (Карточка гражданина.ПередачаКарточки Set end)

                //  *** End programmer edit section *** (Карточка гражданина.ПередачаКарточки Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (Карточка гражданина.ЯвкаГражданина CustomAttributes)

        //  *** End programmer edit section *** (Карточка гражданина.ЯвкаГражданина CustomAttributes)
        public virtual IIS.CZN.DetailArrayOfЯвкаГражданина ЯвкаГражданина
        {
            get
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ЯвкаГражданина Get start)

                //  *** End programmer edit section *** (Карточка гражданина.ЯвкаГражданина Get start)
                if ((this.fЯвкаГражданина == null))
                {
                    this.fЯвкаГражданина = new IIS.CZN.DetailArrayOfЯвкаГражданина(this);
                }
                IIS.CZN.DetailArrayOfЯвкаГражданина result = this.fЯвкаГражданина;
                //  *** Start programmer edit section *** (Карточка гражданина.ЯвкаГражданина Get end)

                //  *** End programmer edit section *** (Карточка гражданина.ЯвкаГражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ЯвкаГражданина Set start)

                //  *** End programmer edit section *** (Карточка гражданина.ЯвкаГражданина Set start)
                this.fЯвкаГражданина = value;
                //  *** Start programmer edit section *** (Карточка гражданина.ЯвкаГражданина Set end)

                //  *** End programmer edit section *** (Карточка гражданина.ЯвкаГражданина Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (Карточка гражданина.ОтметкаГражданина CustomAttributes)

        //  *** End programmer edit section *** (Карточка гражданина.ОтметкаГражданина CustomAttributes)
        public virtual IIS.CZN.DetailArrayOfОтметкаГражданина ОтметкаГражданина
        {
            get
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ОтметкаГражданина Get start)

                //  *** End programmer edit section *** (Карточка гражданина.ОтметкаГражданина Get start)
                if ((this.fОтметкаГражданина == null))
                {
                    this.fОтметкаГражданина = new IIS.CZN.DetailArrayOfОтметкаГражданина(this);
                }
                IIS.CZN.DetailArrayOfОтметкаГражданина result = this.fОтметкаГражданина;
                //  *** Start programmer edit section *** (Карточка гражданина.ОтметкаГражданина Get end)

                //  *** End programmer edit section *** (Карточка гражданина.ОтметкаГражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Карточка гражданина.ОтметкаГражданина Set start)

                //  *** End programmer edit section *** (Карточка гражданина.ОтметкаГражданина Set start)
                this.fОтметкаГражданина = value;
                //  *** Start programmer edit section *** (Карточка гражданина.ОтметкаГражданина Set end)

                //  *** End programmer edit section *** (Карточка гражданина.ОтметкаГражданина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Карточка гражданинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КарточкагражданинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Карточка гражданинаE", typeof(IIS.CZN.Карточка гражданина));
                }
            }
            
            /// <summary>
            /// "Карточка гражданинаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КарточкагражданинаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Карточка гражданинаL", typeof(IIS.CZN.Карточка гражданина));
                }
            }
        }
    }
}
