//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Личность.
    /// </summary>
    //  *** Start programmer edit section *** (Личность CustomAttributes)

    //  *** End programmer edit section *** (Личность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛичностьE", new string[] {
            "ФИО as \'ФИО\'"})]
    [AssociatedDetailViewAttribute("ЛичностьE", "ТрудоваяДеятельность", "ТрудоваяДеятельностьE", true, "", "Трудовая деятельность", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ЛичностьE", "ТрудоваяКнижка", "ТрудоваяКнижкаE", true, "", "Трудовая книжка", true, new string[] {
            ""})]
    [View("ЛичностьL", new string[] {
            "ФИО as \'ФИО\'"})]
    public class Личность : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.CZN.DetailArrayOfТрудоваяДеятельность fТрудоваяДеятельность;
        
        private IIS.CZN.DetailArrayOfТрудоваяКнижка fТрудоваяКнижка;
        
        //  *** Start programmer edit section *** (Личность CustomMembers)

        //  *** End programmer edit section *** (Личность CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        //  *** Start programmer edit section *** (Личность.ФИО CustomAttributes)

        //  *** End programmer edit section *** (Личность.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                //  *** Start programmer edit section *** (Личность.ФИО Get start)

                //  *** End programmer edit section *** (Личность.ФИО Get start)
                string result = this.fФИО;
                //  *** Start programmer edit section *** (Личность.ФИО Get end)

                //  *** End programmer edit section *** (Личность.ФИО Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Личность.ФИО Set start)

                //  *** End programmer edit section *** (Личность.ФИО Set start)
                this.fФИО = value;
                //  *** Start programmer edit section *** (Личность.ФИО Set end)

                //  *** End programmer edit section *** (Личность.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Личность.
        /// </summary>
        //  *** Start programmer edit section *** (Личность.ТрудоваяДеятельность CustomAttributes)

        //  *** End programmer edit section *** (Личность.ТрудоваяДеятельность CustomAttributes)
        public virtual IIS.CZN.DetailArrayOfТрудоваяДеятельность ТрудоваяДеятельность
        {
            get
            {
                //  *** Start programmer edit section *** (Личность.ТрудоваяДеятельность Get start)

                //  *** End programmer edit section *** (Личность.ТрудоваяДеятельность Get start)
                if ((this.fТрудоваяДеятельность == null))
                {
                    this.fТрудоваяДеятельность = new IIS.CZN.DetailArrayOfТрудоваяДеятельность(this);
                }
                IIS.CZN.DetailArrayOfТрудоваяДеятельность result = this.fТрудоваяДеятельность;
                //  *** Start programmer edit section *** (Личность.ТрудоваяДеятельность Get end)

                //  *** End programmer edit section *** (Личность.ТрудоваяДеятельность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Личность.ТрудоваяДеятельность Set start)

                //  *** End programmer edit section *** (Личность.ТрудоваяДеятельность Set start)
                this.fТрудоваяДеятельность = value;
                //  *** Start programmer edit section *** (Личность.ТрудоваяДеятельность Set end)

                //  *** End programmer edit section *** (Личность.ТрудоваяДеятельность Set end)
            }
        }
        
        /// <summary>
        /// Личность.
        /// </summary>
        //  *** Start programmer edit section *** (Личность.ТрудоваяКнижка CustomAttributes)

        //  *** End programmer edit section *** (Личность.ТрудоваяКнижка CustomAttributes)
        public virtual IIS.CZN.DetailArrayOfТрудоваяКнижка ТрудоваяКнижка
        {
            get
            {
                //  *** Start programmer edit section *** (Личность.ТрудоваяКнижка Get start)

                //  *** End programmer edit section *** (Личность.ТрудоваяКнижка Get start)
                if ((this.fТрудоваяКнижка == null))
                {
                    this.fТрудоваяКнижка = new IIS.CZN.DetailArrayOfТрудоваяКнижка(this);
                }
                IIS.CZN.DetailArrayOfТрудоваяКнижка result = this.fТрудоваяКнижка;
                //  *** Start programmer edit section *** (Личность.ТрудоваяКнижка Get end)

                //  *** End programmer edit section *** (Личность.ТрудоваяКнижка Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Личность.ТрудоваяКнижка Set start)

                //  *** End programmer edit section *** (Личность.ТрудоваяКнижка Set start)
                this.fТрудоваяКнижка = value;
                //  *** Start programmer edit section *** (Личность.ТрудоваяКнижка Set end)

                //  *** End programmer edit section *** (Личность.ТрудоваяКнижка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛичностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьE", typeof(IIS.CZN.Личность));
                }
            }
            
            /// <summary>
            /// "ЛичностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьL", typeof(IIS.CZN.Личность));
                }
            }
        }
    }
}
