//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Направление гражданина.
    /// </summary>
    //  *** Start programmer edit section *** (НаправлениеГражданина CustomAttributes)

    //  *** End programmer edit section *** (НаправлениеГражданина CustomAttributes)
    [AutoAltered()]
    [Caption("Направление гражданина")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НаправлениеГражданинаE", new string[0])]
    public class НаправлениеГражданина : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CZN.Карточка гражданина fКарточка гражданина;
        
        //  *** Start programmer edit section *** (НаправлениеГражданина CustomMembers)

        //  *** End programmer edit section *** (НаправлениеГражданина CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CZN.Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (НаправлениеГражданина.Карточка гражданина CustomAttributes)

        //  *** End programmer edit section *** (НаправлениеГражданина.Карточка гражданина CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CZN.Карточка гражданина Карточка гражданина
        {
            get
            {
                //  *** Start programmer edit section *** (НаправлениеГражданина.Карточка гражданина Get start)

                //  *** End programmer edit section *** (НаправлениеГражданина.Карточка гражданина Get start)
                IIS.CZN.Карточка гражданина result = this.fКарточка гражданина;
                //  *** Start programmer edit section *** (НаправлениеГражданина.Карточка гражданина Get end)

                //  *** End programmer edit section *** (НаправлениеГражданина.Карточка гражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (НаправлениеГражданина.Карточка гражданина Set start)

                //  *** End programmer edit section *** (НаправлениеГражданина.Карточка гражданина Set start)
                this.fКарточка гражданина = value;
                //  *** Start programmer edit section *** (НаправлениеГражданина.Карточка гражданина Set end)

                //  *** End programmer edit section *** (НаправлениеГражданина.Карточка гражданина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НаправлениеГражданинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НаправлениеГражданинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НаправлениеГражданинаE", typeof(IIS.CZN.НаправлениеГражданина));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of НаправлениеГражданина.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfНаправлениеГражданина CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfНаправлениеГражданина CustomAttributes)
    public class DetailArrayOfНаправлениеГражданина : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CZN.DetailArrayOfНаправлениеГражданина members)

        //  *** End programmer edit section *** (IIS.CZN.DetailArrayOfНаправлениеГражданина members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type НаправлениеГражданина by index.
        /// </summary>
        /// <summary>
        /// Adds object with type НаправлениеГражданина.
        /// </summary>
        public DetailArrayOfНаправлениеГражданина(IIS.CZN.Карточка гражданина fКарточка гражданина) : 
                base(typeof(НаправлениеГражданина), ((ICSSoft.STORMNET.DataObject)(fКарточка гражданина)))
        {
        }
        
        public IIS.CZN.НаправлениеГражданина this[int index]
        {
            get
            {
                return ((IIS.CZN.НаправлениеГражданина)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CZN.НаправлениеГражданина dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
