//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отметка гражданина.
    /// </summary>
    //  *** Start programmer edit section *** (ОтметкаГражданина CustomAttributes)

    //  *** End programmer edit section *** (ОтметкаГражданина CustomAttributes)
    [AutoAltered()]
    [Caption("Отметка гражданина")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтметкаГражданинаE", new string[0])]
    public class ОтметкаГражданина : ICSSoft.STORMNET.DataObject
    {
        
        private string fОтметка;
        
        private IIS.CZN.КарточкаГражданина fКарточкаГражданина;
        
        //  *** Start programmer edit section *** (ОтметкаГражданина CustomMembers)

        //  *** End programmer edit section *** (ОтметкаГражданина CustomMembers)

        
        /// <summary>
        /// Отметка.
        /// </summary>
        //  *** Start programmer edit section *** (ОтметкаГражданина.Отметка CustomAttributes)

        //  *** End programmer edit section *** (ОтметкаГражданина.Отметка CustomAttributes)
        [StrLen(255)]
        public virtual string Отметка
        {
            get
            {
                //  *** Start programmer edit section *** (ОтметкаГражданина.Отметка Get start)

                //  *** End programmer edit section *** (ОтметкаГражданина.Отметка Get start)
                string result = this.fОтметка;
                //  *** Start programmer edit section *** (ОтметкаГражданина.Отметка Get end)

                //  *** End programmer edit section *** (ОтметкаГражданина.Отметка Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ОтметкаГражданина.Отметка Set start)

                //  *** End programmer edit section *** (ОтметкаГражданина.Отметка Set start)
                this.fОтметка = value;
                //  *** Start programmer edit section *** (ОтметкаГражданина.Отметка Set end)

                //  *** End programmer edit section *** (ОтметкаГражданина.Отметка Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CZN.КарточкаГражданина.
        /// </summary>
        //  *** Start programmer edit section *** (ОтметкаГражданина.КарточкаГражданина CustomAttributes)

        //  *** End programmer edit section *** (ОтметкаГражданина.КарточкаГражданина CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CZN.КарточкаГражданина КарточкаГражданина
        {
            get
            {
                //  *** Start programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Get start)

                //  *** End programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Get start)
                IIS.CZN.КарточкаГражданина result = this.fКарточкаГражданина;
                //  *** Start programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Get end)

                //  *** End programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Set start)

                //  *** End programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Set start)
                this.fКарточкаГражданина = value;
                //  *** Start programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Set end)

                //  *** End programmer edit section *** (ОтметкаГражданина.КарточкаГражданина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтметкаГражданинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтметкаГражданинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтметкаГражданинаE", typeof(IIS.CZN.ОтметкаГражданина));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОтметкаГражданина.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfОтметкаГражданина CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfОтметкаГражданина CustomAttributes)
    public class DetailArrayOfОтметкаГражданина : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CZN.DetailArrayOfОтметкаГражданина members)

        //  *** End programmer edit section *** (IIS.CZN.DetailArrayOfОтметкаГражданина members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОтметкаГражданина by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОтметкаГражданина.
        /// </summary>
        public DetailArrayOfОтметкаГражданина(IIS.CZN.КарточкаГражданина fКарточкаГражданина) : 
                base(typeof(ОтметкаГражданина), ((ICSSoft.STORMNET.DataObject)(fКарточкаГражданина)))
        {
        }
        
        public IIS.CZN.ОтметкаГражданина this[int index]
        {
            get
            {
                return ((IIS.CZN.ОтметкаГражданина)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CZN.ОтметкаГражданина dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
