//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Трудовая деятельность.
    /// </summary>
    //  *** Start programmer edit section *** (ТрудоваяДеятельность CustomAttributes)

    //  *** End programmer edit section *** (ТрудоваяДеятельность CustomAttributes)
    [AutoAltered()]
    [Caption("Трудовая деятельность")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТрудоваяДеятельностьE", new string[0])]
    public class ТрудоваяДеятельность : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CZN.Личность fЛичность;
        
        //  *** Start programmer edit section *** (ТрудоваяДеятельность CustomMembers)

        //  *** End programmer edit section *** (ТрудоваяДеятельность CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CZN.Личность.
        /// </summary>
        //  *** Start programmer edit section *** (ТрудоваяДеятельность.Личность CustomAttributes)

        //  *** End programmer edit section *** (ТрудоваяДеятельность.Личность CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CZN.Личность Личность
        {
            get
            {
                //  *** Start programmer edit section *** (ТрудоваяДеятельность.Личность Get start)

                //  *** End programmer edit section *** (ТрудоваяДеятельность.Личность Get start)
                IIS.CZN.Личность result = this.fЛичность;
                //  *** Start programmer edit section *** (ТрудоваяДеятельность.Личность Get end)

                //  *** End programmer edit section *** (ТрудоваяДеятельность.Личность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ТрудоваяДеятельность.Личность Set start)

                //  *** End programmer edit section *** (ТрудоваяДеятельность.Личность Set start)
                this.fЛичность = value;
                //  *** Start programmer edit section *** (ТрудоваяДеятельность.Личность Set end)

                //  *** End programmer edit section *** (ТрудоваяДеятельность.Личность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТрудоваяДеятельностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТрудоваяДеятельностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТрудоваяДеятельностьE", typeof(IIS.CZN.ТрудоваяДеятельность));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТрудоваяДеятельность.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfТрудоваяДеятельность CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfТрудоваяДеятельность CustomAttributes)
    public class DetailArrayOfТрудоваяДеятельность : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CZN.DetailArrayOfТрудоваяДеятельность members)

        //  *** End programmer edit section *** (IIS.CZN.DetailArrayOfТрудоваяДеятельность members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТрудоваяДеятельность by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТрудоваяДеятельность.
        /// </summary>
        public DetailArrayOfТрудоваяДеятельность(IIS.CZN.Личность fЛичность) : 
                base(typeof(ТрудоваяДеятельность), ((ICSSoft.STORMNET.DataObject)(fЛичность)))
        {
        }
        
        public IIS.CZN.ТрудоваяДеятельность this[int index]
        {
            get
            {
                return ((IIS.CZN.ТрудоваяДеятельность)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CZN.ТрудоваяДеятельность dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
