//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Явка гражданина.
    /// </summary>
    //  *** Start programmer edit section *** (ЯвкаГражданина CustomAttributes)

    //  *** End programmer edit section *** (ЯвкаГражданина CustomAttributes)
    [AutoAltered()]
    [Caption("Явка гражданина")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЯвкаГражданинаE", new string[0])]
    public class ЯвкаГражданина : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CZN.Карточка гражданина fКарточка гражданина;
        
        //  *** Start programmer edit section *** (ЯвкаГражданина CustomMembers)

        //  *** End programmer edit section *** (ЯвкаГражданина CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CZN.Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (ЯвкаГражданина.Карточка гражданина CustomAttributes)

        //  *** End programmer edit section *** (ЯвкаГражданина.Карточка гражданина CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CZN.Карточка гражданина Карточка гражданина
        {
            get
            {
                //  *** Start programmer edit section *** (ЯвкаГражданина.Карточка гражданина Get start)

                //  *** End programmer edit section *** (ЯвкаГражданина.Карточка гражданина Get start)
                IIS.CZN.Карточка гражданина result = this.fКарточка гражданина;
                //  *** Start programmer edit section *** (ЯвкаГражданина.Карточка гражданина Get end)

                //  *** End programmer edit section *** (ЯвкаГражданина.Карточка гражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЯвкаГражданина.Карточка гражданина Set start)

                //  *** End programmer edit section *** (ЯвкаГражданина.Карточка гражданина Set start)
                this.fКарточка гражданина = value;
                //  *** Start programmer edit section *** (ЯвкаГражданина.Карточка гражданина Set end)

                //  *** End programmer edit section *** (ЯвкаГражданина.Карточка гражданина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЯвкаГражданинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЯвкаГражданинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЯвкаГражданинаE", typeof(IIS.CZN.ЯвкаГражданина));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЯвкаГражданина.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfЯвкаГражданина CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfЯвкаГражданина CustomAttributes)
    public class DetailArrayOfЯвкаГражданина : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CZN.DetailArrayOfЯвкаГражданина members)

        //  *** End programmer edit section *** (IIS.CZN.DetailArrayOfЯвкаГражданина members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЯвкаГражданина by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЯвкаГражданина.
        /// </summary>
        public DetailArrayOfЯвкаГражданина(IIS.CZN.Карточка гражданина fКарточка гражданина) : 
                base(typeof(ЯвкаГражданина), ((ICSSoft.STORMNET.DataObject)(fКарточка гражданина)))
        {
        }
        
        public IIS.CZN.ЯвкаГражданина this[int index]
        {
            get
            {
                return ((IIS.CZN.ЯвкаГражданина)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CZN.ЯвкаГражданина dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
